# Type stubs for PyQt5.QtChart
from typing import Any

class QChart: ...
class QChartView: ...
class QLineSeries: ...
class QScatterSeries: ...
class QValueAxis: ...
class QDateTimeAxis: ...

__all__: Any
