# Type stubs for PyQt5.QtCore
from typing import Any

class Qt: ...
class QThread: ...
class pyqtSignal: ...
class QTimer: ...
class QEvent: ...
class QObject: ...
class QUrl: ...
class QSize: ...
class QRect: ...
class QPoint: ...

__all__: Any
