# Type stubs for PyQt5.QtGui
from typing import Any

class QFont: ...
class QColor: ...
class QIcon: ...
class QImage: ...
class QPixmap: ...
class QPalette: ...
class QBrush: ...
class QPen: ...

__all__: Any
