# Type stubs for PyQt5
from typing import Any

class QWidget: ...
class QVBoxLayout: ...
class QHBoxLayout: ...
class QLabel: ...
class QPushButton: ...
class QLineEdit: ...
class QGridLayout: ...
class QGroupBox: ...
class QTextEdit: ...
class QFileDialog: ...
class QApplication: ...
class QMainWindow: ...
class QMessageBox: ...
class QDialog: ...
class QComboBox: ...
class QSpinBox: ...
class QDoubleSpinBox: ...
class QCheckBox: ...
class QRadioButton: ...
class QSlider: ...
class QProgressBar: ...
class QTableWidget: ...
class QListWidget: ...
class QPlainTextEdit: ...

__all__: Any
